### ISSUE TITLE
Is the L2 regularization working as intended?

### ISSUE THREAD

**Issue by Quenjy** [jfutoma/MGP-RNN#4]
Hello,

As I was rereading parts of your code in order to add some extra elements to the pipeline, I noticed that the code you used to determine the regularization seemed wrong. 

Here is your code
```
with tf.variable_scope("", reuse=True):
    loss_reg = L2_penalty * tf.reduce_sum(tf.square(out_weights))
    for i in range(n_layers):
        loss_reg = L2_penalty + tf.reduce_sum(
            tf.square(tf.get_variable('rnn/multi_rnn_cell/cell_' + str(i) + '/basic_lstm_cell/kernel')))
```

It seems to me like you're overwriting loss_reg everytime, instead of summing the contribution of every weight to the total regularization. In the end, the only weight that gets taken into consideration is that of the final LSTM cell.

Here is the code I replaced the above with

```
with tf.variable_scope("", reuse=True):
    loss_reg = L2_penalty * tf.reduce_sum(tf.square(out_weights))
    for i in range(n_layers):
        loss_reg = loss_reg + L2_penalty * tf.reduce_sum(
            tf.square(tf.get_variable('rnn/multi_rnn_cell/cell_' + str(i) + '/basic_lstm_cell/kernel')))
```

Am I correct in my assumption that your code contained an error, or am I misunderstanding something?

**Comment by jfutoma** [comment]
Yup you're absolutely right - good catch! I'm not sure how that slipped past me.  I don't have this bug in the most up to date version of the code I've been using, so I'll have to make the change here as well.  Thanks for making me aware!
