### ISSUE TITLE
project help 

### ISSUE THREAD

**Issue by Auhan99** [jfutoma/MGP-RNN#6]
hey , 
I am ayushman singh third year IIT BHU ,
I want to work on stepsis detection can you help me get started, I read some papers but am having some trouble in getting data as at  most of it is not freely available 
thanks

**Comment by jfutoma** [comment]
Unfortunately most healthcare data is not publicly available, this is just the state of the field right now.  I would recommend getting access to MIMIC, a freely available ICU dataset: https://mimic.physionet.org/ . I would also encourage you to try to find a collaborator who is actually a clinician or who has a medical background, as it will make working with healthcare data much easier, both on the preprocessing side and on the higher level framing of research questions (e.g., does it even make sense to build a model to predict X?)

**Comment by Auhan99** [comment]
okay thanks
